'use client';

import '../globals.css';

import { usePathname } from 'next/navigation';
import { EnhancedToolbar } from '@/components/enhanced-toolbar';
import { useScrollHeaderState } from '@/components/integrated-scroll-header';

// Note: This metadata export needs to be in a separate file for client components
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const { isScrolled } = useScrollHeaderState();

  // Determine page title based on pathname
  const getPageTitle = () => {
    if (pathname === '/about') return 'About';
    if (pathname.startsWith('/projects')) return 'Projects';
    return 'My App';
  };

  // Determine scroll title based on pathname
  const getScrollTitle = () => {
    if (pathname === '/about') return 'About Andrew';
    if (pathname.startsWith('/projects')) return 'My Projects';
    return undefined;
  };

  return (
    <>
      <EnhancedToolbar title={getPageTitle()} scrollTitle={getScrollTitle()} isScrolled={isScrolled} />
      <div className="container mx-auto max-w-4xl px-6 py-8">{children}</div>
    </>
  );
}
